[general]
import = [
    "~/.config/alacritty/themes/themes/gruber_darker.toml"
]

[window]
padding.x = 13
padding.y = 13

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "Iosevka Nerd Font"
bold.family = "Iosevka Nerd Font"
italic.family = "Iosevka Nerd Font"
bold_italic.family = "Iosevka Nerd Font"

size = 17.0
